### PR TITLE
Update dependencies (winreg, toml)

### PR DESCRIPTION
**Pull request by poliorcetics**
- deps: winreg 0.11
- deps: toml 0.7

I haven't seen an MSRV so I think updating is okay, don't hesitate to tell me if there is one, I can check.

### CODE REVIEW

**Comment by poliorcetics** [comment]
Nothing from those deps is in the public API I think, so a minor release should be enough ?

**Comment by nabijaczleweli** [comment]
The MSRV was soft 1.35.0 before `v1.3.3`, then hard 1.35.0 before `v1.8.0`, then soft 1.36.0 before `v2.0.0`, it's now soft 1.45.0, cf. these tags.

I've given up on exceedingly hard MSRVs here; well, unless it's something insanely fresh like 1.65, but if it passes AppVeyor's 1.45 it's obviously fine.

**Comment by poliorcetics** [comment]
TOML 0.7 has an MSRV or 1.60: https://github.com/toml-rs/toml/blob/main/crates/toml/Cargo.toml#L18, is that okay ?

**Comment by nabijaczleweli** [comment]
I wouldn't say that delights me per se, since bullseye ships 1.48, but apparently bookworm will soon enough land with 1.63, so meh.

Let's see how https://ci.appveyor.com/project/nabijaczleweli/rust-embed-resource/builds/46642053 fares.

**Comment by nabijaczleweli** [comment]
Applied as 379654f780f9d151518f43c7ef7c26fd0bcd74be and 7d56960ba8f77acfd6c9bdf9cbbd07621eafb940, released in [v2.1.1](https://github.com/nabijaczleweli/rust-embed-resource/releases/tag/v2.1.1).

**Pull request closed without merging**
