### PR TITLE
Add support for cross-compilation to windows on linux

### PR DESCRIPTION
**Pull request by SonnyX**

### CODE REVIEW

**Comment by SonnyX** [comment]
Do not merge: breaks compiling from linux to linux.

**Comment by nabijaczleweli** [comment]
Is this available on compile-time (via `env!(TARGET)`/`cfg!(something)`/somesuch)?

Doing `if let Ok(target) = std::env::var("TARGET")` twice kinda (okay, a lot) sucks, especially if `SUPPORTED` is universally `true` now

**Comment by SonnyX** [comment]
Sadly it is not possible to achieve this on compile-time, see: 
https://github.com/rust-lang/cargo/issues/4423

Although not the prettiest of solutions, a valid one none-the-less, polling std::env twice should not have any impact on anyone's performance.

**Comment by nabijaczleweli** [comment]
Hmm, alright, then, I'll merge this as is, refactor to dedupe, since that's my major concern, and not performance, and I'll ask you to test the refactored version to see if I fucked something up in the process

**Comment by nabijaczleweli** [comment]
If you could check with the above commit on the `master` branch, that'd be *lovely*

**Comment by SonnyX** [comment]
I've verified the code, this is indeed the way it should be done.
I've run tests for linux->linux, and linux->windows builds on the most recent commit. It works as intended. Both work as intended.
I cannot test windows->windows, so I assume you will verify that yourself.

Thanks for merging!

**Comment by nabijaczleweli** [comment]
Dope

Released in [`v1.3.0`](https://github.com/nabijaczleweli/rust-embed-resource/releases/tag/v1.3.0)

**Pull request merged**
